<!DOCTYPE html>
<html>
<head>
    <title>User Profile</title>
    <style>
        .alert-success {
            background-color: #D4EDDA; /* Зеленый фон */
            border-color: #C3E6CB; /* Зеленая рамка */
            color: #155724; /* Зеленый текст */
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid transparent;
            border-radius: 4px;
        }
    </style>
</head>
<body>
<h1>User Profile</h1>

<?php if (!empty($messages['success'])): ?>
    <div class="alert alert-success">
        <?= $messages['success'][0] ?>
    </div>
<?php endif ?>

<p><strong>Nickname:</strong> <?= $user['name'] ?></p>
<p><strong>Email:</strong> <?= $user['email'] ?></p>
<a href="/users">Back to Users</a>
<!-- Добавляем кнопку для редактирования пользователя, передавая URL для редактирования пользователя из параметров -->
<a href="<?= $router->urlFor('edit_user', ['name' => $user['name']]) ?>">Edit User</a>
<form action="<?= $router->urlFor('delete_user', ['name' => $user['name']]) ?>" method="post" onsubmit="return confirm('Вы уверены, что хотите удалить этого пользователя?');">
    <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Delete User">
</form>
</body>
</html>
